[INFO 22:33:29] pymarl Running command 'my_main'
[INFO 22:33:29] pymarl Started run with ID "389"
